### PR TITLE
Changed the POST server arguments.

### PR DESCRIPTION
**Pull request by tmanuszak**
post params were incorrect for generate_workload's api call.

### CODE REVIEW

**Comment by rajrkane** [comment]
That parameter just needs to match the http payload in the `send_one_request` function. The files upload fine, so what's incorrect?

**Comment by rajrkane** [comment]
I changed it from myfile to image to reflect that it's uploading an image. Shouldn't affect anything

**Comment by tmanuszak** [comment]
They are testing us on the workload script. The workload script isnt calling "/images", its calling"/".

I agree it would make more sense. I just thought they were going to use the command in their repo directly. https://github.com/nehavadnere/CSE546_Sum22_workload_generator

**Comment by rajrkane** [comment]
Ahh, you're right. Word

**Comment by rajrkane** [comment]
The rest of the changes I made in the script don't affect anything functionally relative to the grading script, so no need for changes there. Merging

**Pull request merged**
